### ISSUE TITLE
error while run docker-compose up -d

### ISSUE THREAD

**Issue by ecojuntak** [Delpro-Club/regrader#1]
![screenshot from 2016-04-27 23 32 30](https://cloud.githubusercontent.com/assets/9149602/14859963/b1d35696-0cd0-11e6-92e8-8563333daa26.png)
i found this error while run docker-compose up -d,
i have retry to run but it show the same error..

**Comment by hierony94** [comment]
Sorry for not to state it in the Beginning.
The Regrader container using port 80 and the mysql container use port 3306.
Please ensure that the port isn't used by other program.

If I'm assuming you using apache2 as the web server in the local, please kindly run `sudo service apache2 stop` and then run `docker compose up -d`.

**Comment by ecojuntak** [comment]
the problem solve,

the apache2 and mysql services must stopped first

**Comment by hierony94** [comment]
I Will Closed this issue then.

Just as Suggestions, You can disable Apache2 and mysql to start on boot time.
So you don't have to stop it each time your computer start.
